### ISSUE TITLE
Utils `get_remote` doesn't work with `.ssh/config` aliases

### ISSUE THREAD

**Issue by dharrigan** [pwntester/octo.nvim#295]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

Using `Octo issue list`, I'm receiving this error `Post "https://github/api/graphql": x509: certificate.....`

### Describe what you expected to happen

I'm able to retrieve the issue list

### How to reproduce it (as minimally and precisely as possible)

1. Create a `~/.ssh/config' file
2. Add the following 
```
host github
    hostname github.com
    user git
```
3. Clone a repo `git clone ssh://github/foo/bar`
4. Try to do `Octo issue list`

### Tell us your environment

`Linux daffy 5.17.9-arch1-1`
`NVIM v0.7.0`

Latest Octo

### Anything else we need to know?

I think the issue here is from https://github.com/pwntester/octo.nvim/blob/5517cbdf302be2abc4ac43e5b8b2a812d0222bbb/lua/octo/utils.lua#L169  it's expecting a particular format for the git repo. Then at line https://github.com/pwntester/octo.nvim/blob/5517cbdf302be2abc4ac43e5b8b2a812d0222bbb/lua/octo/utils.lua#L184 it's spliting it, assuming there is a `@` in the host and that the hostname also is in two parts, i.e., `github.com` not `github`.

Changing the `.git/confg` to read `git@github.com` results in successful retrieval of issues.

**Comment by pwntester** [comment]
hhmm, seems like the only solution would be to parse the ssh config which I dont think should be done by Octo. Can you think of any other solution or workaround?

**Comment by pwntester** [comment]
This should be fixed now. But you need to define the aliases in your setup config:

  `ssh_aliases = {["github"] = "github.com"}`

**Comment by artistic-nucleus** [comment]
Hey, adding ssh_aliases is still not working for me..Can you help?
