### ISSUE TITLE
No way to identify if PR is Draft or not.

### ISSUE THREAD

**Issue by daliusd** [pwntester/octo.nvim#453]
## Issue Description

In PR view you don't see if PR is in Draft state.

### Describe what happened (or what feature you want)

No way to identify if PR is Draft or not.

### Describe what you expected to happen

I expect to see line indicating that PR is Draft (if it is).

### How to reproduce it (as minimally and precisely as possible)

1. Run `:Octo pr list` and select PR that is draft

**Comment by HampusMat** [comment]
I did some investigating and definitely should set virtual text to `[DRAFT]` as seen here
https://github.com/pwntester/octo.nvim/blob/5a04268e54c3f538702ef4f03f635d69c569d23e/lua/octo/ui/writers.lua#L196-L202

I'll do further investigating

**Comment by pwntester** [comment]
Sorry for missing this issue. Should be fixed now

**Comment by HampusMat** [comment]
It still doesn't show in previews
![2024-01-18-22:00](https://github.com/pwntester/octo.nvim/assets/87620379/744882a8-20d5-41cd-8f06-e599164f90b7)

**Comment by HampusMat** [comment]
I was able to fix the preview problem with the following change
```diff
--- a/lua/octo/pickers/telescope/previewers.lua
+++ b/lua/octo/pickers/telescope/previewers.lua
@@ -38,6 +38,14 @@ local issue = defaulter(function(opts)
               elseif entry.kind == "pull_request" then
                 obj = result.data.repository.pullRequest
               end
+
+                         OctoBuffer:new {
+                               bufnr = bufnr,
+                               number = obj.number,
+                               repo = entry.repo,
+                               node = obj,
+                         }
+
               writers.write_title(bufnr, obj.title, 1)
               writers.write_details(bufnr, obj)
               writers.write_body(bufnr, obj)
```

The `write_state` function relies on there being a buffer in the `octo_buffers` table but there is none when called from the callback which is called after running Github CLI in the issue previewer

**Comment by pwntester** [comment]
Thanks @HampusMat Would you mind opening a PR please?

**Comment by HampusMat** [comment]
Sure
